[package]
name = "kurbo"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
keywords = ["graphics", "curves", "geometry"]

[dependencies]
arrayvec = "0.4.10"
